name: Deploy to Render

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.15.1 # Specify your Node.js version
     
      - name: Install Dependencies
        run: npm ci
      
      - name: Install Type Definitions
        run: yarn add --dev @types/node @types/express # Add other type definitions as needed
        
        
      - name: Build
        run: npm run build # Replace with your build command if needed
        
      - name: Deploy to Render
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }} # Ensure you have this secret set in your repository settings
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/srv-cqnr43dds78s739fau40/deploys \
            -d '{"branch":"main"}' # Adjust the branch as needed
